name: run test and deploy
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: environment test
        run: echo "hey"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami
  