name: run test and deploy
on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: environment test
        run: echo "hey"
      - name: executing remote ssh commands using password
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.KEY }}
          REMOTE_HOST: ${ { secrets.HOST }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }
  