name: run test and deploy
on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: environment test
        run: echo "hey"
      - name: executing remote ssh commands using password
        uses: easingthemes/ssh-deploy@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami
  